// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewSubscription struct {
	To int `json:"to"`
}

type NewTweet struct {
	Text string `json:"text"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Tweet struct {
	ID     int    `json:"id"`
	UserID int    `json:"userId"`
	Text   string `json:"text"`
}
